// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIB9yuWepTmPjyHBgp6skZQxICNr2NRhA',
    appId: '1:8005080628:web:b1ed921060fa2500d6dc61',
    messagingSenderId: '8005080628',
    projectId: 'nti-course-project1',
    authDomain: 'nti-course-project1.firebaseapp.com',
    storageBucket: 'nti-course-project1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9hm88EOfhFkVJ8yqwv6KQifbk4q_vcZs',
    appId: '1:8005080628:android:a77bec7412e40eb1d6dc61',
    messagingSenderId: '8005080628',
    projectId: 'nti-course-project1',
    storageBucket: 'nti-course-project1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZi8-7cBoQl31fehzUVa1my4niEEDg9rE',
    appId: '1:8005080628:ios:08b98bdd18c47a5dd6dc61',
    messagingSenderId: '8005080628',
    projectId: 'nti-course-project1',
    storageBucket: 'nti-course-project1.firebasestorage.app',
    iosBundleId: 'com.example.ntiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZi8-7cBoQl31fehzUVa1my4niEEDg9rE',
    appId: '1:8005080628:ios:08b98bdd18c47a5dd6dc61',
    messagingSenderId: '8005080628',
    projectId: 'nti-course-project1',
    storageBucket: 'nti-course-project1.firebasestorage.app',
    iosBundleId: 'com.example.ntiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIB9yuWepTmPjyHBgp6skZQxICNr2NRhA',
    appId: '1:8005080628:web:d0e32fbdc820be2ed6dc61',
    messagingSenderId: '8005080628',
    projectId: 'nti-course-project1',
    authDomain: 'nti-course-project1.firebaseapp.com',
    storageBucket: 'nti-course-project1.firebasestorage.app',
  );
}
